#!/usr/bin/python

import socket
import executil
from sysversion import fmt_sysversion

def fmt_welcome():
    welcome = "Welcome to %s" % socket.gethostname().capitalize()

    sysversion = fmt_sysversion()
    if sysversion:
        welcome += ", " + sysversion

    return welcome

def indent(level, s):
    return "\n".join([ (" " * level + line) 
                       for line in s.splitlines() ])

def main():
    print(fmt_welcome())

    try:
        turnkey_sysinfo = executil.getoutput("turnkey-sysinfo")
        print()
        print(indent(2, turnkey_sysinfo))
        print()
    except executil.ExecError:
        pass

if __name__ == "__main__":
    main()
