#!/usr/bin/python3

import socket
from subprocess import run, PIPE
from sys import stdin

from sysversion import fmt_sysversion

encoding = stdin.encoding # most likely 'utf-8'

def fmt_welcome(encoding=encoding):
    welcome = "Welcome to {}".format(socket.gethostname().capitalize())

    sysversion = fmt_sysversion(encoding=encoding)
    if sysversion:
        welcome += ", " + sysversion

    return welcome  # returns string obj

def indent(level, s, encoding=encoding):
    return "\n".join([(" " * level + line) for line in s.splitlines()])

def main(encoding=encoding):
    print(fmt_welcome(encoding=encoding))

    turnkey_sysinfo = run(["turnkey-sysinfo"], stdout=PIPE).stdout.decode(encoding)
    print()
    print(indent(2, turnkey_sysinfo))
    print()

if __name__ == "__main__":
    main()
